stages:
  - build
  - test

build:
  stage: build
  script:
    - ip a
    - apt install wget -y
    - cat /etc/*release
    - hostname
    - date

test:
  stage: test
  script:
    - echo "testing custom runner"