stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir /tmp/deneme
    - cd /tmp/deneme
    - echo "Onur Yasarlar" > /tmp/deneme/test.out

test:
  stage: test
  script:
    - echo "testing custom runner"