stages:
  - build
  - test

build:
  stage: build
  script:
    - /usr/sbin/ip addr show
    - /usr/bin/sudo yum install wget -y
    - /usr/bin/cat /etc/*release
    - /usr/bin/hostname
    - /usr/bin/date
    - /usr/bin/pwd

test:
  stage: test
  script:
    - echo "testing custom runner"