stages:
  - build
  - test

build:
  stage: build
  scripts:
    - mkdir /tmp/deneme
    - cd /tmp/deneme
    - echo "Onur Yasarlar" > /tmp/deneme

test:
  stage: test
  scripts:
    - echo "testing custom runner"